import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/headers/Navbar";
import Contact from "@/components/footer/Contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Satria Nusa Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Contact />
      </body>
    </html>
  );
}
